// <auto-generated />
using System;
using DiscordWhoIs.Core.Databases.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiscordWhoIs.Core.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20260116020530_SplitAliasedAuthors")]
    partial class SplitAliasedAuthors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("AuthorFanfic", b =>
                {
                    b.Property<int>("AuthorsAuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FanficsFanficId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuthorsAuthorId", "FanficsFanficId");

                    b.HasIndex("FanficsFanficId");

                    b.ToTable("AuthorFanfic");
                });

            modelBuilder.Entity("DiscordWhoIs.Core.Databases.DbModels.Alias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AliasUserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("AliasName")
                        .UseCollation("NOCASE");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AuthorId");

                    b.HasKey("Id");

                    b.HasIndex("AliasUserName")
                        .IsUnique();

                    b.HasIndex("AuthorId");

                    b.ToTable("Alias");
                });

            modelBuilder.Entity("DiscordWhoIs.Core.Databases.DbModels.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ao3ProfileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("DiscordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscordUsername")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FanficNetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FanficNetProfileName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorId");

                    b.HasIndex("Ao3ProfileName")
                        .IsUnique();

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.HasIndex("DiscordUsername")
                        .IsUnique();

                    b.HasIndex("FanficNetId")
                        .IsUnique();

                    b.HasIndex("FanficNetProfileName")
                        .IsUnique();

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("DiscordWhoIs.Core.Databases.DbModels.Fanfic", b =>
                {
                    b.Property<int>("FanficId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookmarksCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChapterCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommentCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FicLastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("HitCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KudosCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Warnings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WordCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("FanficId");

                    b.ToTable("Fanfics");
                });

            modelBuilder.Entity("AuthorFanfic", b =>
                {
                    b.HasOne("DiscordWhoIs.Core.Databases.DbModels.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsAuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordWhoIs.Core.Databases.DbModels.Fanfic", null)
                        .WithMany()
                        .HasForeignKey("FanficsFanficId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiscordWhoIs.Core.Databases.DbModels.Alias", b =>
                {
                    b.HasOne("DiscordWhoIs.Core.Databases.DbModels.Author", "Author")
                        .WithMany("Aliases")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("DiscordWhoIs.Core.Databases.DbModels.Author", b =>
                {
                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
