<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UserSecretsId>6d51e116-b485-451a-8e50-14788ee6e5a6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiscordWhoIs.Core\DiscordWhoIs.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Discord.Net" Version="3.18.0" />
  </ItemGroup>

	<ItemGroup>
		<TrimmerRootDescriptor Include="Linker.xml" />
	</ItemGroup>
	<ItemGroup>
		<None Update="Linker.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>